#ijob -c1 -p standard -A berglandlab
#module load gcc/7.1.0  openmpi/3.1.4 R/3.6.0; R

### libraries
  library(data.table)
  library(foreach)
  library(doMC)
  registerDoMC(20)
  library(cowplot)

### load haplotype prior file
  #dat <- fread("/scratch/aob2x/daphnia_hwe_sims/trioPhase/testTrio.consensus.header.phase.csv")
  dat <- fread("/mnt/sammas_storage/bergland-lab/alan/testTrio.consensus.header.phase.csv")

  setnames(dat, c(1,2), c("chr", "pos"))

  dat <- dat[!(A=="1/1" & B=="1/1")][!(A=="0/0" & B=="0/0")]

  dat.p <- dat[,list(ref=REF, alt=ALT,
                      A1=as.numeric(substr(A, 0, 1)),
                      A2=as.numeric(substr(A, 3, 3)),
                      B1=as.numeric(substr(B, 0, 1)),
                      B2=as.numeric(substr(B, 3, 3))),
                  list(chr, pos)]

  dat.ag <- dat[,list(.N, max=max(pos)), chr]
  dat.ag <- dat.ag[N>1000]
  dat.ag[,id:=1:12]

  setkey(dat.p, chr)
  dat.p <- dat.p[J(dat.ag$chr)]
  dat.p[,id:=c(1:dim(dat.p)[1])]

  dat.pl <- melt(dat.p, id.vars=c("chr", "pos", "ref", "alt", "id"), variable.name="haplotype")
  setkey(dat.pl, chr, pos, id, haplotype)

### load output from harp (generated by `plotHarp.R`)
  #load(file="/scratch/aob2x/daphnia_hwe_sims/harp_pools/summarizedOut/harpWins.Rdata")
  load("/mnt/sammas_storage/bergland-lab/alan/harpWins.Rdata")
  setkey(o, chr)

### iterate through per SNP
  haf <- foreach(i=c(1:dim(dat.p)[1]))%dopar%{
    #i<-1

    if(i%%1000==0) print(paste(i, dim(dat.p)[1], sep=" / "))
    tmp <- dat.p[i]

    tmp.ag <- o[J(tmp$chr)][start<=tmp$pos & stop>=tmp$pos][,list(chr=tmp$chr, pos=tmp$pos,
                                                        freq=c(mean(pA1), mean(pA2), mean(pB1), mean(pB2)),
                                                        haplotype=c("A1", "A2", "B1", "B2")),
                                                    list(pool)]
    setkey(tmp.ag, chr, pos, haplotype)

    tmp.m <- merge(tmp.ag, dat.pl)

    tmp.m[,list(est.f=weighted.mean(abs(1-value), freq),
                exp.f=mean(abs(1-value)),
                haps=paste(abs(1-value), collapse="")),
           list(pool, chr, pos, id)]
  }
  haf <- rbindlist(haf)

  save(haf, file="/mnt/sammas_storage/bergland-lab/alan/haf.Rdata")

### compare with empirical estimates
  load("/mnt/sammas_storage/bergland-lab/alan/totalADRDlongall.Rdata")
  setnames(geno, "Sample", "pool")

  setkey(geno, chr, pos, pool)
  setkey(haf, chr, pos, pool)

  foo <- merge(geno[,c("chr", "pos", "ref", "pool", "alt", "propalt"),with=F], haf)
  foo[,A1:=as.numeric(substr(haps, 0, 1))]
  foo[,A2:=as.numeric(substr(haps, 2, 2))]
  foo[,B1:=as.numeric(substr(haps, 3, 3))]
  foo[,B2:=as.numeric(substr(haps, 4, 4))]

  foo[,A:=A1+A2]
  foo[,B:=B1+B2]

  foo[,BA.delta:=B-A]

  foo.ag <- foo[,list(male=c(mean(est.f[grepl("Male", pool)]), mean(propalt[grepl("Male", pool)]), mean(exp.f[grepl("Male", pool)])),
                      pe=c(mean(est.f[grepl("PE", pool)]), mean(propalt[grepl("PE", pool)]), mean(exp.f[grepl("PE", pool)])),
                      class=c("est.f", "obs.f", "exp.f")),
                 list(chr, pos, id, BA.delta)]

### sliding window

### generate windows
  chrs <- foo.ag[, list(min=min(pos), max=max(pos)), chr]
  window.bp <- 50000
  step.bp <- 5000

  wins <- foreach(i=1:dim(chrs)[1], .combine="rbind")%dopar%{
    #i<-1
    print(i)
    tmp <- data.table(chr=chrs[i]$chr, start=seq(from=chrs[i]$min, to=chrs[i]$max-window.bp, by=step.bp))
    tmp[,stop:=start+window.bp]
    tmp
  }
  wins[,i:=1:dim(wins)[1]]

  setkey(foo.ag, chr, pos)

### run SW analysis

  o <- foreach(i=c(1:dim(wins)[1]), .errorhandling="remove")%dopar%{
    #i<-145167 ; i <- 58987
    #i <- wins[chr=="Scaffold_7757_HRSCAF_8726"][which.min(abs(start-8660157))]$i
    #i <- wins[chr=="Scaffold_6786_HRSCAF_7541"][which.min(abs(start-12960054))]$i
    if(i%%100==0) print(paste(i, dim(wins)[1], sep=" / "))


    foo.ag[,win:=0]
    foo.ag[chr==wins$chr[i] & pos>=wins$start[i] & pos<=wins$stop[i], win:=1]

    #mod <- summary(lm(log2(or)~((BA.geno.diff))*win, m.inform))
    mod <- summary(lm((male-pe)~BA.delta*win, foo.ag[class=="est.f"]))
    mod <- summary(lm((male-pe)~BA.delta*win, foo.ag[class=="obs.f"]))

    #mod <- summary(lm(I(male-pe)~BA.delta*win, foo.ag[class=="est.f"]))

    data.table(win.i=i, chr=wins$chr[i], start=wins$start[i], stop=wins$stop[i], nSNPs=sum(foo.ag$win),
              r2=mod$r.squared,
              beta.int=mod$coefficients[4,1],
              se=mod$coefficients[4,2],
              p=(mod$coefficients[4,4]))


  #data.table(win.i=i, chr=wins$chr[i], start=wins$start[i], stop=wins$stop[i], nSNPs=sum(m.inform$win),
  #         p=anova(mod)$P[3])

    }
    o <- rbindlist(o)
    o[,pa:=p.adjust(p, "bonferroni")]
    o[,ppa:=(sign(beta.int)*log10(pa))]

    ggplot(data=o[nSNPs>25], aes(y=(ppa), x=win.i, color=chr)) + geom_line()



   foo.ag[,win:=0]
   foo.ag[chr=="Scaffold_7757_HRSCAF_8726" & pos>=8660084 & pos<=8710084, win:=1]

   t1 <- summary(lm(I(male-pe)~BA.delta*win, foo.ag))





  ggplot(data=foo.ag[1:10000], aes(x=as.factor(BA.delta), y=male)) + geom_violin() + facet_wrap(~class)

  plot(male~BA.delta, foo.ag[1:100])

  est.bp <- ggplot(data=foo, aes(est.f, x=exp.f, group=interaction(pool, exp.f), color=pool)) + geom_boxplot() + geom_hline(yintercept=c(.25, .5, .75))
  obs.bp <- ggplot(data=foo, aes(propalt, x=exp.f, group=interaction(pool, exp.f), color=pool)) + geom_boxplot() + geom_hline(yintercept=c(.25, .5, .75))

  plot_grid(est.bp, obs.bp)

  plot(propalt~est.f, foo[1:100000])
  plot(propalt~exp.f, foo[1:100000])
  boxplot(est.f~exp.f, foo[1:100000])
  boxplot(propalt~exp.f, foo[1:100000])

  abline(h=c(.25, .5, .75))

### twiddles

  haf[,diff:=est.f - exp.f]

  ggplot(data=haf, aes(x=id, y=diff, group=pool, color=pool)) + geom_line()



  foo.ag <- foo[,list(male=c(mean(est.f[grepl("Male", pool)]), mean(propalt[grepl("Male", pool)]), mean(exp.f[grepl("Male", pool)])),
                      pe=c(mean(est.f[grepl("PE", pool)]), mean(propalt[grepl("PE", pool)]), mean(exp.f[grepl("PE", pool)]))),
                 list(chr, pos, id, BA.delta)]

  haf.ag[,diff:=log(male/pe)]

  ggplot(data=haf.ag, aes(x=id, y=abs(diff), color=chr)) + geom_line()
