#!/usr/bin/env Rscript

### libraries
  library(SeqArray)
  library(data.table)
  library(foreach)
  library(doMC)
  registerDoMC(20)
  library(ggplot2)
  library(SNPRelate)
  library(tidyverse)

  ############
  ### args ###
  ############

  args=commandArgs(trailingOnly=TRUE)
  varA=args[1]
  varB=args[2]
  varC=args[3]

### open genotype file
genofile <- seqOpen("/scratch/kbb7sh/Daphnia/MappingDecember2019/MapJune2020_ann_90.seq.gds")

allsnps <- data.table(variant.ids = seqGetData(genofile, "variant.id"),
    chr = seqGetData(genofile, "chromosome"),
    pos = seqGetData(genofile, "position"))
allsnps[,final.use:=T]


###Use non LD pruned dataset
  load("dpfiltsnps_20200722.Rdata")
  filtsnptb <- dpfiltsnps
  colnames(filtsnptb) <- c("oldvariantids", "chr", "pos", "olddp")

### Filter SNPs
  snps <- data.table(variant.ids = seqGetData(genofile, "variant.id"),
      chr = seqGetData(genofile, "chromosome"),
      pos = seqGetData(genofile, "position"))
  setkey(snps, chr, pos)
  setkey(filtsnptb, chr, pos)
  msnps <- merge(filtsnptb, snps)
  msnps[,final.use:=T]

### Load superclone file
  sc <- fread("/scratch/kbb7sh/Daphnia/MappingDecember2019/June2020/Superclones201617182019withObtusaandPulicaria_kingcorr_20200623_wmedrd.txt")

### Do some filtering on read depth and independence
  scrd5 <- sc[medrd>4 & Nonindependent==0 & LabGenerated==0 & clone!="April5_2018_D8_Male2"]
  subscrd5 <- scrd5[, c("clone", "SC", "population", "year", "Sex", "Species", "medrd"), with=FALSE]
  clonestouse <- subscrd5
  clonestouseids <- clonestouse$clone

### make windows
  setkey(allsnps, chr, pos)

  chr.ag <- allsnps[,list(start = min(pos), stop=max(pos)), list(chr)]
  chr.ag$length <- chr.ag$stop-chr.ag$start
  chrtouse <- chr.ag$chr[chr.ag$length>1000000]

  window.size <- 250000
  step.size <- 10000
  wins <- foreach(chr.i=chrtouse, .combine="rbind")%dopar%{
    #chr.i <- "Scaffold_1863_HRSCAF_2081"
    snp.dt.ag <- allsnps[J(chr.i)][(final.use), list(start=min(pos), stop=max(pos))]

    data.table(chr=chr.i, start=seq(from=snp.dt.ag$start,
                                    to=snp.dt.ag$stop - window.size,
                                    by=step.size),
                          stop =seq(from=snp.dt.ag$start,
                                    to=snp.dt.ag$stop - window.size,
                                    by=step.size) + window.size)
  }

  ### Maybe look at how many SNPs go into each window/tree? Perhaps there are some low ones that are throwing things off?
  msnpcount <- foreach(win.i = c(1:dim(wins)[1]), .combine="rbind", .errorhandling="remove")%dopar%{

    print(paste("Getting data: ", win.i, sep=""))

    snp.dt.tmp <- msnps[J(wins[win.i]$chr)][pos>=wins[win.i]$start & pos<=wins[win.i]$stop][(final.use)]

    tmp <- data.table(window=win.i, numsnps=dim(snp.dt.tmp)[1])
    tmp

  }

  wins$numsnps <- msnpcount$numsnps
  winstouse <- wins[numsnps>500]


### run windows
  m <- foreach(win.i = c(1:10), .combine="rbind", .errorhandling="remove")%dopar%{
  #m <- foreach(win.i =varA:varB, .errorhandling="remove", .combine="rbind")%dopar%{

    print(paste("Getting data: ", win.i, sep=""))

    snp.dt.tmp <- msnps[J(winstouse[win.i]$chr)][pos>=winstouse[win.i]$start & pos<=winstouse[win.i]$stop][(final.use)]

    seqResetFilter(genofile)
    seqSetFilter(genofile, variant.id=snp.dt.tmp$variant.ids, sample.id=clonestouseids)

    #First lets try IBS with we keep SNPs present in 1 individuals
		### set some global parameters
				maf <- 0.001
				missing.rate <- 0.15
				threads <- 10

				ibs <- snpgdsIBS(genofile, snp.id=snp.dt.tmp$variant.ids, sample.id=clonestouseids, num.thread=20, maf=maf,
							missing.rate=0.15, autosome.only = FALSE)

			### a bit of re-formating of the ibs matrix
				ibs.mat <- ibs$ibs
				rownames(ibs.mat) <- ibs$sample.id
				colnames(ibs.mat) <- ibs$sample.id

			### make the IBs matrix long form
        ibs.matdt <- as.data.table(ibs.mat)
        setkey(clonestouse, clone)
        ibs.matdt$cloneA <- clonestouse$clone
        ibs.long<- melt(ibs.matdt, measure.vars=clonestouseids, variable.name="cloneB", value.name="IBS")
				ibs.long <- na.omit(ibs.long)

        # First let's remove all identical comparisons from ibs.long
  				ibs.longnoident <- ibs.long[ibs.long$cloneA!=ibs.long$cloneB]
          ibs.longnoident$cloneA <- as.factor(ibs.longnoident$cloneA)

  			#Let's also remove duplicated comparisons - how to do this?
  				ibs.longnoident$cloneAnum <- as.numeric(ibs.longnoident$cloneA)
          tmpnum <- data.table(cloneB=ibs.longnoident$cloneA, cloneBnum=ibs.longnoident$cloneAnum)
          tmpnumu <- unique(tmpnum)
          setkey(ibs.longnoident, cloneB)
          setkey(tmpnumu, cloneB)
          mibs.longnoident <- merge(ibs.longnoident, tmpnumu)
  				mibs.longnoident$CloneNumComb <- ifelse(mibs.longnoident$cloneAnum > mibs.longnoident$cloneBnum,
  					paste(mibs.longnoident$cloneAnum,mibs.longnoident$cloneBnum,sep="_"),
  					paste(mibs.longnoident$cloneBnum,mibs.longnoident$cloneAnum,sep="_"))
  				setkey(mibs.longnoident, CloneNumComb)
  				ibs.longnoidentunique <- unique(mibs.longnoident, by="CloneNumComb")
  			#Now get back to the original three columns
  				ibs.longunique <- data.table(cloneA=ibs.longnoidentunique$cloneA,
  					cloneB=ibs.longnoidentunique$cloneB, IBS=ibs.longnoidentunique$IBS)

        ibs.longunique$chr <- c(winstouse[win.i]$chr)
        ibs.longunique$start <- c(winstouse[win.i]$start)
        ibs.longunique$stop <- c(winstouse[win.i]$stop)
        ibs.longunique$window <- c(win.i)
        ibs.longunique

  }

   save(m, file=paste("m_IBSbyslidingwindow_250000_10000_withpulicariaandobtusa_20200724_", varC, ".Rdata", sep=""))

  #!/usr/bin/env Rscript

  ### libraries
    library(data.table)
    library(foreach)
    library(ggplot2)
    library(tidyverse)

    ############
    ### args ###
    ############

    args=commandArgs(trailingOnly=TRUE)
    varA=args[1]

  ### Let's work through one input file first
    load(paste("m_IBSbyslidingwindow_250000_10000_withpulicariaandobtusa_20200629_", varA, ".Rdata", sep=""))

  # Load superclone file
    sc <- fread("/scratch/kbb7sh/Daphnia/MappingDecember2019/June2020/Superclones201617182019withObtusaandPulicaria_kingcorr_20200623_wmedrd.txt")

  # Add in superclone information
    scsubA <- data.table(cloneA=sc$clone, SCA=sc$SC, popA=sc$population, yearA=sc$year, medrdA=sc$medrd, speciesA=sc$Species, sexA=sc$Sex)
    scsubB <- data.table(cloneB=sc$clone, SCB=sc$SC, popB=sc$population, yearB=sc$year, medrdB=sc$medrd, speciesB=sc$Species, sexB=sc$Sex)
    setkey(scsubA, cloneA)
    setkey(scsubB, cloneB)
    setkey(m, cloneB)
    mtmp <- merge(m, scsubB)
    setkey(mtmp, cloneA)
    msc <- merge(mtmp, scsubA)

  # Now add in new composite superclone info columns, start with making new OO SCs
    msc$SCA_B <- ifelse(msc$SCA=="OO", paste(msc$SCA, msc$cloneA, sep="_"), msc$SCA)
    msc$SCB_B <- ifelse(msc$SCB=="OO", paste(msc$SCB, msc$cloneB, sep="_"), msc$SCB)
    msc$compinfo <- paste(msc$SCA_B, msc$popA, msc$SCB_B, msc$popB, sep="_")
    msc$SCcomp <- paste(msc$SCA, msc$SCB, sep="_")

  # Now I will make two separate files, first I will make one file with all AxC comparisons, then a file that contains no A and C, and a file that contains only A and C compared to everyone else
    mscACcomp <- msc[SCcomp=="A_C" | SCcomp=="C_A"]
    mscnoAC <- msc[SCA!="A" & SCA!="C" & SCB!="A" & SCB!="C"]
    mscnoACcomp <- msc[SCcomp!="A_C" | SCcomp!="C_A"]
    mscACvsrest <- mscnoACcomp[SCA=="A" | SCA=="C" | SCB=="A" | SCB=="C"]
    mscothervsObtusaPulicaria <- mscnoAC[SCA=="G" | SCA=="P" | SCB=="G" | SCB=="P"]
    mscothervsObtusaPulicaria <- mscothervsObtusaPulicaria[SCcomp!="P_P" & SCcomp!="G_G"]

  # First aggregate the A vs C comparisons
    mscACcomp <- mscACcomp[popA!="DMud" & popB!="DMud"]
    mscACcomp$SCcomp <- ifelse(mscACcomp$SCcomp=="C_A", "A_C", mscACcomp$SCcomp)
    mscACcomp.ag <- mscACcomp[,list(meanIBS=mean(IBS), sd_IBS=sd(IBS)),
      list(window, chr, start, stop, speciesA, speciesB)]
    mscACcomp.ag$SCA_C=c("A")
    mscACcomp.ag$SCB_C=c("C")
    mscACcomp.ag$ACvspond=c("A_D8DBunk_C_D8DBunk")

    # Now let's aggregate the file comparing A and C to everyone else
    # Start with A versus everyone
      mscACvsrest_A <- mscACvsrest[SCA=="A" | SCB=="A"]
    # Just get's too complicated, try pulling out just A vs Ws and D10
      mscACvsrest_AW <- mscACvsrest_A[popA=="W1" | popA=="W6" | popA=="D10" | popB=="W1" | popB=="W6" | popB=="D10"]
      mscACvsrest_AW$ACvspond <- ifelse(mscACvsrest_AW$popA=="W1" | mscACvsrest_AW$popB=="W1", "A_W1", ifelse(
        mscACvsrest_AW$popA=="W6" | mscACvsrest_AW$popB=="W6", "A_W6", "A_D10"))
      mscACvsrest_AW$SCA_C <- c("A")
      mscACvsrest_AW$SCB_C <- ifelse(mscACvsrest_AW$SCB_B=="A", mscACvsrest_AW$SCA_B, mscACvsrest_AW$SCB_B)

      mscACvsrest_AW.ag <- mscACvsrest_AW[,list(meanIBS=mean(IBS), sd_IBS=sd(IBS)),
        list(window, chr, start, stop, speciesA, speciesB, SCA_C, SCB_C, ACvspond)]

      mscACvsrest_PO <- mscACvsrest_A[speciesA=="obtusa" | speciesB=="obtusa" | speciesA=="pulicaria" | speciesB=="pulicaria"]
      mscACvsrest_PO$ACvspond <- ifelse(mscACvsrest_PO$speciesA=="obtusa" | mscACvsrest_PO$speciesB=="obtusa", "A_obtusa", "A_pulicaria")
      mscACvsrest_PO$SCA_C <- c("A")
      mscACvsrest_PO$SCB_C <- ifelse(mscACvsrest_PO$SCB_B=="A", mscACvsrest_PO$SCA_B, mscACvsrest_PO$SCB_B)

      mscACvsrest_PO.ag <- mscACvsrest_PO[,list(meanIBS=mean(IBS), sd_IBS=sd(IBS)),
          list(window, chr, start, stop, SCA_C, SCB_C, ACvspond)]
      mscACvsrest_PO.ag$speciesA <- c("pulex")
      mscACvsrest_PO.ag$speciesB <- ifelse(mscACvsrest_PO.ag$ACvspond=="A_pulicaria", "pulicaria", "obtusa")

    # Do the same with C
    # Start with C versus everyone
      mscACvsrest_C <- mscACvsrest[SCA=="C" | SCB=="C"]
    # Just get's too complicated, try pulling out just A vs Ws and D10
      mscACvsrest_CW <- mscACvsrest_C[popA=="W1" | popA=="W6" | popA=="D10" | popB=="W1" | popB=="W6" | popB=="D10"]
      mscACvsrest_CW$ACvspond <- ifelse(mscACvsrest_CW$popA=="W1" | mscACvsrest_CW$popB=="W1", "C_W1", ifelse(
        mscACvsrest_CW$popA=="W6" | mscACvsrest_CW$popB=="W6", "C_W6", "C_D10"))
      mscACvsrest_CW$SCA_C <- c("C")
      mscACvsrest_CW$SCB_C <- ifelse(mscACvsrest_CW$SCB_B=="C", mscACvsrest_CW$SCA_B, mscACvsrest_CW$SCB_B)

      mscACvsrest_CW.ag <- mscACvsrest_CW[,list(meanIBS=mean(IBS), sd_IBS=sd(IBS)),
        list(window, chr, start, stop, speciesA, speciesB, SCA_C, SCB_C, ACvspond)]

      mscACvsrest_POB <- mscACvsrest_C[speciesA=="obtusa" | speciesB=="obtusa" | speciesA=="pulicaria" | speciesB=="pulicaria"]
      mscACvsrest_POB$ACvspond <- ifelse(mscACvsrest_POB$speciesA=="obtusa" | mscACvsrest_POB$speciesB=="obtusa", "A_obtusa", "A_pulicaria")
      mscACvsrest_POB$SCA_C <- c("C")
      mscACvsrest_POB$SCB_C <- ifelse(mscACvsrest_POB$SCB_B=="C", mscACvsrest_POB$SCA_B, mscACvsrest_POB$SCB_B)

      mscACvsrest_POB.ag <- mscACvsrest_POB[,list(meanIBS=mean(IBS), sd_IBS=sd(IBS)),
          list(window, chr, start, stop, SCA_C, SCB_C, ACvspond)]
      mscACvsrest_POB.ag$speciesA <- c("pulex")
      mscACvsrest_POB.ag$speciesB <- ifelse(mscACvsrest_POB.ag$ACvspond=="A_pulicaria", "pulicaria", "obtusa")

      mscACvsrest.ag <- rbind(mscACvsrest_AW.ag, mscACvsrest_CW.ag, mscACcomp.ag)

      mscACvsrest_POBC <- rbind(mscACvsrest_PO.ag, mscACvsrest_POB.ag)

      save(mscACvsrest.ag, file=paste("mscACvsrest.ag_", varA, ".Rdata", sep=""))

      save(mscACvsrest_POBC, file=paste("mscACvsrest_POBC_", varA, ".Rdata", sep=""))

### Now lets work on D8, DBunk, DCat excluding A and C.

#!/usr/bin/env Rscript

### libraries
  library(data.table)
  library(foreach)
  library(ggplot2)
  library(tidyverse)

  ############
  ### args ###
  ############

  args=commandArgs(trailingOnly=TRUE)
  varA=args[1]

### Let's work through one input file first
  load(paste("m_IBSbyslidingwindow_250000_10000_withpulicariaandobtusa_20200629_", varA, ".Rdata", sep=""))

# Load superclone file
  sc <- fread("/scratch/kbb7sh/Daphnia/MappingDecember2019/June2020/Superclones201617182019withObtusaandPulicaria_kingcorr_20200623_wmedrd.txt")
  sc$population <- str_replace(sc$population, "Dcat", "DCat")

# Add in superclone information
  scsubA <- data.table(cloneA=sc$clone, SCA=sc$SC, popA=sc$population, yearA=sc$year, medrdA=sc$medrd, speciesA=sc$Species, sexA=sc$Sex)
  scsubB <- data.table(cloneB=sc$clone, SCB=sc$SC, popB=sc$population, yearB=sc$year, medrdB=sc$medrd, speciesB=sc$Species, sexB=sc$Sex)
  setkey(scsubA, cloneA)
  setkey(scsubB, cloneB)
  setkey(m, cloneB)
  mtmp <- merge(m, scsubB)
  setkey(mtmp, cloneA)
  msc <- merge(mtmp, scsubA)

# Now add in new composite superclone info columns, start with making new OO SCs
  msc$SCA_B <- ifelse(msc$SCA=="OO", paste(msc$SCA, msc$cloneA, sep="_"), msc$SCA)
  msc$SCB_B <- ifelse(msc$SCB=="OO", paste(msc$SCB, msc$cloneB, sep="_"), msc$SCB)
  msc$compinfo <- paste(msc$SCA_B, msc$popA, msc$SCB_B, msc$popB, sep="_")
  msc$SCcomp <- paste(msc$SCA, msc$SCB, sep="_")

# And I will make a file to compare all non A and C lineages from the three focal ponds to the outgroup species

    mscnoAC <- msc[SCA!="A" & SCA!="C" & SCB!="A" & SCB!="C"]
    mscothervsObtusaPulicaria <- mscnoAC[SCA=="G" | SCA=="P" | SCB=="G" | SCB=="P"]
    mscothervsObtusaPulicaria <- mscothervsObtusaPulicaria[SCcomp!="P_P" & SCcomp!="G_G"]
    mscothervsObtusaPulicaria <- mscothervsObtusaPulicaria[popA!="D10" & popB!="D10" &
      popA!="DLily" & popB!="DLily" & popA!="DOil" & popB!="DOil" & popA!="Dramp" &
      popB!="Dramp" & popA!="W1" & popB!="W1" & popA!="W6" & popB!="W6"]
    mscothervsObtusaPulicaria$ACvspond <- ifelse(mscothervsObtusaPulicaria$speciesA=="obtusa" |
      mscothervsObtusaPulicaria$speciesB=="obtusa", "D8DBunkDCatvsObtusa", "D8DBunkDCatvsPulicaria")
    mscothervsObtusaPulicaria$SCcompB <- ifelse(mscothervsObtusaPulicaria$SCA_B >
      mscothervsObtusaPulicaria$SCB_B, paste(mscothervsObtusaPulicaria$SCA_B,
      mscothervsObtusaPulicaria$SCB_B, sep="_"), paste(mscothervsObtusaPulicaria$SCB_B, mscothervsObtusaPulicaria$SCA_B, sep="_"))
    mscothervsObtusaPulicaria$SCA_C <- mscothervsObtusaPulicaria$SCA_B
    mscothervsObtusaPulicaria$SCB_C <- mscothervsObtusaPulicaria$SCB_B

    D8DBunkDCatvsPO.ag <- mscothervsObtusaPulicaria[,list(meanIBS=mean(IBS), sd_IBS=sd(IBS)),
      list(window, chr, start, stop, speciesA, speciesB, SCA_C, SCB_C, ACvspond)]

    save(D8DBunkDCatvsPO.ag, file=paste("D8DBunkDCatvsPO.ag_", varA, ".Rdata", sep=""))

  # Pull out D10, W ponds versus three focal ponds
    mscnoACD10W <- mscnoAC[popA=="D10" | popB=="D10" | popA=="W1" | popB=="W1" | popA=="W6" | popB=="W6"]
    mscnoACD10W <- mscnoACD10W[SCA!="P" & SCB!="P" & SCA!="G" & SCB!="G"]
    mscnoACD10W <- mscnoACD10W[popB!="DLily" & popB!="DOil" & popB!="Dramp"]
    mscnoACD10W <- mscnoACD10W[SCA_B!=SCB_B]
    mscnoACD10W$SCcompB <- ifelse(mscnoACD10W$SCA_B > mscnoACD10W$SCB_B, paste(mscnoACD10W$SCA_B,
    mscnoACD10W$SCB_B, sep="_"), paste(mscnoACD10W$SCB_B, mscnoACD10W$SCA_B, sep="_"))
    mscnoACD10W <- mscnoACD10W[popA!=popB]
    mscnoACD10W$SCA_C <- ifelse(mscnoACD10W$SCA_B > mscnoACD10W$SCB_B, mscnoACD10W$SCA_B, mscnoACD10W$SCB_B)
    mscnoACD10W$SCB_C <- ifelse(mscnoACD10W$SCA_B > mscnoACD10W$SCB_B, mscnoACD10W$SCB_B, mscnoACD10W$SCA_B)
    mscnoACD10W$ACvspond <- paste(mscnoACD10W$popA, mscnoACD10W$popB, sep="_")
    mscnoACD10W$ACvspond <- ifelse(mscnoACD10W$ACvspond=="D10_D8", "D8_D10", ifelse(mscnoACD10W$ACvspond=="D10_DBunk",
    "DBunk_D10", ifelse(mscnoACD10W$ACvspond=="D10_DCat", "DCat_D10", ifelse(mscnoACD10W$ACvspond=="W1_D8", "D8_W1",
    ifelse(mscnoACD10W$ACvspond=="W6_D8", "D8_W6", ifelse(mscnoACD10W$ACvspond=="W1_DCat", "DCat_W1", ifelse(
    mscnoACD10W$ACvspond=="W6_DCat", "DCat_W6", ifelse(mscnoACD10W$ACvspond=="W1_DBunk", "DBunk_W1", ifelse(
    mscnoACD10W$ACvspond=="W6_DBunk", "DBunk_W6", mscnoACD10W$ACvspond)))))))))
    mscnoACD10W <- mscnoACD10W[ACvspond!="W1_D10" & ACvspond!="W6_D10" & ACvspond!="W6_W1"]

    D8DBunkDCatvsD10W.ag <- mscnoACD10W[,list(meanIBS=mean(IBS), sd_IBS=sd(IBS)),
      list(window, chr, start, stop, speciesA, speciesB, SCA_C, SCB_C, ACvspond)]

    save(D8DBunkDCatvsD10W.ag, file=paste("D8DBunkDCatvsD10W.ag_", varA, ".Rdata", sep=""))


  # Pull out just D8 and DBunk and DCat
    mscnoAC$popA <- ifelse(mscnoAC$popA=="Dcat", "DCat", mscnoAC$popA)
    mscnoAC$popB <- ifelse(mscnoAC$popB=="Dcat", "DCat", mscnoAC$popB)
    mscD8DBunk <- mscnoAC[popA=="D8" | popA=="DBunk" | popA=="DCat"]
    mscD8DBunkB <- mscD8DBunk[popB=="D8" | popB=="DBunk" | popB=="DCat"]
    mscD8DBunkB <- mscD8DBunkB[SCA_B!=SCB_B]
    mscD8DBunkB <- mscD8DBunkB[speciesA!="obtusa" & speciesB!="obtusa"]
    mscD8DBunkB$SCcompB <- ifelse(mscD8DBunkB$SCA_B > mscD8DBunkB$SCB_B, paste(mscD8DBunkB$SCA_B,
    mscD8DBunkB$SCB_B, sep="_"), paste(mscD8DBunkB$SCB_B, mscD8DBunkB$SCA_B, sep="_"))
    mscD8DBunkB$SCA_C <- ifelse(mscD8DBunkB$SCA_B > mscD8DBunkB$SCB_B, mscD8DBunkB$SCA_B, mscD8DBunkB$SCB_B)
    mscD8DBunkB$SCB_C <- ifelse(mscD8DBunkB$SCA_B > mscD8DBunkB$SCB_B, mscD8DBunkB$SCB_B, mscD8DBunkB$SCA_B)
    mscD8DBunkB$ACvspond <- paste(mscD8DBunkB$popA, mscD8DBunkB$popB, sep="_")
    mscD8DBunkB$ACvspond <- ifelse(mscD8DBunkB$ACvspond=="DBunk_D8", "D8_DBunk", ifelse(
    mscD8DBunkB$ACvspond=="DCat_D8", "D8_DCat", ifelse(mscD8DBunkB$ACvspond=="DCat_DBunk",
    "DBunk_DCat", mscD8DBunkB$ACvspond)))

    D8DBunkDCat.ag <- mscD8DBunkB[,list(meanIBS=mean(IBS), sd_IBS=sd(IBS)),
      list(window, chr, start, stop, speciesA, speciesB, SCA_C, SCB_C, ACvspond)]

    save(D8DBunkDCat.ag, file=paste("D8DBunkDCat.ag_", varA, ".Rdata", sep=""))


#!/usr/bin/env Rscript

    ### libraries
      library(data.table)
      library(foreach)
      library(ggplot2)
      library(tidyverse)

  ### Load processed IBS by window files
      inputfiles <- list.files(path="/scratch/kbb7sh/Daphnia/MappingDecember2019/recalibrate90/", pattern="mscACvsrest.ag_B_")

      totalibsag <- foreach(i=1:length(inputfiles), .combine="rbind")%do%{
        f=paste("/scratch/kbb7sh/Daphnia/MappingDecember2019/recalibrate90/", inputfiles[i], sep="")
        load(f)
        mscACvsrest.ag
      }

      inputfilesPO <- list.files(path="/scratch/kbb7sh/Daphnia/MappingDecember2019/recalibrate90/", pattern="mscACvsrest_POBC")

      totalibsagPO <- foreach(i=1:length(inputfilesPO), .combine="rbind")%do%{
        f=paste("/scratch/kbb7sh/Daphnia/MappingDecember2019/recalibrate90/", inputfilesPO[i], sep="")
        load(f)
        mscACvsrest_POBC
      }

      totalibsagPO$ACvspond <- ifelse(totalibsagPO$ACvspond=="A_obtusa" & totalibsagPO$SCA_C=="C", "C_obtusa", ifelse(
        totalibsagPO$ACvspond=="A_pulicaria" & totalibsagPO$SCA_C=="C", "C_pulicaria", totalibsagPO$ACvspond
      ))

      inputfilesDBunkD8 <- list.files(path="/scratch/kbb7sh/Daphnia/MappingDecember2019/recalibrate90/", pattern="D8DBunkDCat.ag")

      totalibsagD8DBunk <- foreach(i=1:length(inputfilesDBunkD8), .combine="rbind")%do%{
        f=paste("/scratch/kbb7sh/Daphnia/MappingDecember2019/recalibrate90/", inputfilesDBunkD8[i], sep="")
        load(f)
        D8DBunkDCat.ag
      }


      inputfilesObtusaPulicaria <- list.files(path="/scratch/kbb7sh/Daphnia/MappingDecember2019/recalibrate90/", pattern="D8DBunkDCatvsPO.ag")

      totalibsObPul <- foreach(i=1:length(inputfilesObtusaPulicaria), .combine="rbind")%do%{
        f=paste("/scratch/kbb7sh/Daphnia/MappingDecember2019/recalibrate90/", inputfilesObtusaPulicaria[i], sep="")
        load(f)
        D8DBunkDCatvsPO.ag
      }


      inputfilesD10W <- list.files(path="/scratch/kbb7sh/Daphnia/MappingDecember2019/recalibrate90/", pattern="D8DBunkDCatvsD10W.ag")

      totalibsD10W <- foreach(i=1:length(inputfilesD10W), .combine="rbind")%do%{
        f=paste("/scratch/kbb7sh/Daphnia/MappingDecember2019/recalibrate90/", inputfilesD10W[i], sep="")
        load(f)
        D8DBunkDCatvsD10W.ag
      }

### Read in only G files first to figure out how to make the figure

      #load("mscACvsrest.ag_F.Rdata")
      #totalibsag <- mscACvsrest.ag

      #load("mscACvsrest_POBC_G.Rdata")
      #totalibsagPO <- mscACvsrest_POBC

      #totalibsagPO$ACvspond <- ifelse(totalibsagPO$ACvspond=="A_obtusa" & totalibsagPO$SCA_C=="C", "C_obtusa", ifelse(
      #  totalibsagPO$ACvspond=="A_pulicaria" & totalibsagPO$SCA_C=="C", "C_pulicaria", totalibsagPO$ACvspond
      #))

      #load("D8DBunkDCat.ag_G.Rdata")
      #totalibsagD8DBunk <- D8DBunkDCat.ag

      #load("D8DBunkDCatvsD10W.ag_G.Rdata")
      #totalibsD10W <- D8DBunkDCatvsD10W.ag

      #load("D8DBunkDCatvsPO.ag_G.Rdata")
      #totalibsObPul <- D8DBunkDCatvsPO.ag

      total <- rbind(totalibsag, totalibsagPO, totalibsagD8DBunk, totalibsD10W, totalibsObPul)

      total$ACvspondB <- ifelse(total$ACvspond=="D8_D10" | total$ACvspond=="DBunk_D10" |
        total$ACvspond=="DCat_D10", "D8DBunkDCatvsD10", ifelse(total$ACvspond=="D8_W1" |
        total$ACvspond=="DBunk_W1" | total$ACvspond=="DCat_W1", "D8DBunkDCatvsW1", ifelse(
        total$ACvspond=="D8_W6" | total$ACvspond=="DBunk_W6" | total$ACvspond=="DCat_W6",
        "D8DBunkDCatvsW6", total$ACvspond
        )))

      total$type <- ifelse(total$ACvspondB=="A_D8DBunk_C_D8DBunk", "AvsC", ifelse(
        total$ACvspondB=="D8_D8" | total$ACvspondB=="DBunk_DBunk" | total$ACvspondB=="DCat_DCat",
        "withinpond", ifelse(total$ACvspondB=="D8_DBunk" | total$ACvspondB=="D8_DCat" |
        total$ACvspondB=="DBunk_DCat", "betweenpond", ifelse(total$ACvspondB=="A_D10" |
        total$ACvspondB=="A_W1" | total$ACvspondB=="A_W6" | total$ACvspondB=="A_pulicaria" |
        total$ACvspondB=="A_obtusa", "Avsout", ifelse(total$ACvspondB=="C_D10" |
        total$ACvspondB=="C_W1" | total$ACvspondB=="C_W6" | total$ACvspondB=="C_pulicaria" |
        total$ACvspondB=="C_obtusa", "Cvsout", "othervsout"
      )))))

      total$type <- factor(total$type, levels=c("AvsC", "withinpond", "betweenpond",
        "Avsout", "Cvsout", "othervsout"))
      total$ACvspondB <- factor(total$ACvspondB, levels=c("A_D8DBunk_C_D8DBunk",
        "D8_D8", "DBunk_DBunk", "DCat_DCat", "D8_DBunk", "D8_DCat", "DBunk_DCat", "A_D10",
        "A_W1", "A_W6", "A_pulicaria", "A_obtusa", "C_D10", "C_W1", "C_W6", "C_pulicaria",
        "C_obtusa", "D8DBunkDCatvsD10", "D8DBunkDCatvsW1", "D8DBunkDCatvsW6",
        "D8DBunkDCatvsPulicaria", "D8DBunkDCatvsObtusa"))

      boxwhiskerIBS <- ggplot(data=total, aes(x=ACvspondB, y=meanIBS, color=as.factor(type))) + geom_boxplot()
      ggsave(boxwhiskerIBS, file="boxwhiskerIBS.pdf")

+ facet_wrap(~type, scales="free_x")


      totalibsObPulObonly <- totalibsObPul[speciesA=="obtusa" | speciesB=="obtusa"]
      totalibsObPulObonlyD8DBunk <- totalibsObPulObonly[popA=="D8" | popB=="D8" | popA=="DBunk" | popB=="DBunk"]

      totalibsObPulObonlyD8DBunk$outlier <- ifelse(totalibsObPulObonlyD8DBunk$meanIBS > 0.6, 1, 0)
      totalibsObPulObonlyD8DBunknoDbarborpulicaria <- totalibsObPulObonlyD8DBunk[popA!="Dbarb" & popB!="Dbarb" & speciesA!="pulicaria" & speciesB!="pulicaria"]


      ggplot(data=totalibsObPulObonlyD8DBunknoDbarborpulicaria, aes(x=as.factor(window), y=meanIBS, color=as.factor(outlier))) + geom_point() +
        facet_wrap(~chr, scales="free_x")

        ggplot(data=totalibsObPulObonlyD8DBunknoDbarborpulicaria[chr=="Scaffold_6786_HRSCAF_7541"], aes(x=as.factor(window), y=meanIBS, color=as.factor(outlier))) + geom_point()
        ggplot(data=totalibsObPulObonlyD8DBunknoDbarborpulicaria[chr=="Scaffold_6786_HRSCAF_7541" & window > 5250 & window < 5430], aes(x=as.factor(window), y=meanIBS, color=as.factor(outlier))) + geom_point()
        ggplot(data=totalibsObPulObonlyD8DBunknoDbarborpulicaria[chr=="Scaffold_1863_HRSCAF_2081"], aes(x=as.factor(window), y=meanIBS, color=as.factor(outlier))) + geom_point()

      totalibsObPulObonlyDCat <- totalibsObPulObonly[popA=="DCat" | popB=="DCat"]
      totalibsObPulObonlyDCat$outlier <- ifelse(totalibsObPulObonlyDCat$meanIBS > 0.6, 1, 0)
      totalibsObPulObonlyDCatnoDbarborpulicaria <- totalibsObPulObonlyDCat[popA!="Dbarb" & popB!="Dbarb" & speciesA!="pulicaria" & speciesB!="pulicaria"]

      ggplot(data=totalibsObPulObonlyDCatnoDbarborpulicaria, aes(x=as.factor(window), y=meanIBS, color=as.factor(outlier))) + geom_point() +
        facet_wrap(~chr, scales="free_x")
      ggplot(data=totalibsObPulObonlyDCatnoDbarborpulicaria[chr=="Scaffold_6786_HRSCAF_7541" & window > 5250 & window < 5430], aes(x=as.factor(window), y=meanIBS, color=as.factor(outlier))) + geom_point()

      totalibsObPulObonlyDD10 <- totalibsObPulObonly[popA=="D10" | popB=="D10"]
      totalibsObPulObonlyDD10$outlier <- ifelse(totalibsObPulObonlyDD10$meanIBS > 0.6, 1, 0)
      totalibsObPulObonlyDD10noDbarborpulicaria <- totalibsObPulObonlyDD10[popA!="Dbarb" & popB!="Dbarb" & speciesA!="pulicaria" & speciesB!="pulicaria"]

      ggplot(data=totalibsObPulObonlyDD10noDbarborpulicaria, aes(x=as.factor(window), y=meanIBS, color=as.factor(outlier))) + geom_point() +
        facet_wrap(~chr, scales="free_x")
      ggplot(data=totalibsObPulObonlyDD10noDbarborpulicaria[chr=="Scaffold_6786_HRSCAF_7541" & window > 5250 & window < 5430], aes(x=as.factor(window), y=meanIBS, color=as.factor(outlier))) + geom_point()

      totalibsObPulObonlyW1 <- totalibsObPulObonly[popA=="W1" | popB=="W1"]
      totalibsObPulObonlyW1$outlier <- ifelse(totalibsObPulObonlyW1$meanIBS > 0.6, 1, 0)
      totalibsObPulObonlyW1noDbarborpulicaria <- totalibsObPulObonlyW1[popA!="Dbarb" & popB!="Dbarb" & speciesA!="pulicaria" & speciesB!="pulicaria"]

      ggplot(data=totalibsObPulObonlyW1noDbarborpulicaria, aes(x=as.factor(window), y=meanIBS, color=as.factor(outlier))) + geom_point() +
        facet_wrap(~chr, scales="free_x")
      ggplot(data=totalibsObPulObonlyW1noDbarborpulicaria[chr=="Scaffold_6786_HRSCAF_7541" & window > 5250 & window < 5430], aes(x=as.factor(window), y=meanIBS, color=as.factor(outlier))) + geom_point()


      totalibsObPulPulonly <- totalibsObPul[speciesA=="pulicaria" | speciesB=="pulicaria"]
      totalibsObPulPulonlyD8DBunk <- totalibsObPulPulonly[popA=="D8" | popB=="D8" | popA=="DBunk" | popB=="DBunk"]

      totalibsObPulPulonlyD8DBunk$outlier <- ifelse(totalibsObPulPulonlyD8DBunk$meanIBS > 0.6, 1, 0)
      totalibsObPulPulonlyD8DBunknoDbarborobtusa <- totalibsObPulPulonlyD8DBunk[popA!="Dbarb" & popB!="Dbarb" & speciesA!="obtusa" & speciesB!="obtusa"]


      ggplot(data=totalibsObPulPulonlyD8DBunknoDbarborobtusa, aes(x=as.factor(window), y=meanIBS)) + geom_point() +
        facet_wrap(~chr, scales="free_x")

        ggplot(data=totalibsObPulPulonlyD8DBunknoDbarborobtusa[chr=="Scaffold_6786_HRSCAF_7541"], aes(x=as.factor(window), y=meanIBS, color=as.factor(outlier))) + geom_point()
        ggplot(data=totalibsObPulPulonlyD8DBunknoDbarborobtusa[chr=="Scaffold_6786_HRSCAF_7541" & window > 5250 & window < 5430], aes(x=as.factor(window), y=meanIBS, color=as.factor(outlier))) + geom_point()


### trial with subset of data
    #load("mscACvsrest.ag_20200424_G.Rdata")
    #load("mscACvsrest_POBC_20200424G.Rdata")
    #load("mscD8DBunknoAC_20200424G.Rdata")

    mscD8DBunkBnoAC.ag <- totalibsagD8DBunk

    colnames(mscD8DBunkBnoAC.ag) <- c("window", "chr", "start", "stop", "SCA_C",
      "SCB_C", "yearA", "yearB", "popA", "popB", "compinfo", "speciesA",
      "speciesB", "meanIBS", "sd_IBS")

    mscD8DBunkBnoAC.ag$ACvspond <- paste(mscD8DBunkBnoAC.ag$popA, mscD8DBunkBnoAC.ag$popB, sep="_")

    mscD8DBunkBnoAC.ag$SCcompare <- mscD8DBunkBnoAC.ag$ACvspond
    mscD8DBunkBnoAC.ag <- mscD8DBunkBnoAC.ag[speciesA!="obtusa" & speciesB!="obtusa"]

    mscD8DBunkBnoAC.agsub <- mscD8DBunkBnoAC.ag[, c("window", "chr", "start", "stop", "SCA_C",
      "SCB_C", "ACvspond", "meanIBS", "sd_IBS", "speciesA", "speciesB"), with=FALSE]

    mscD8DBunkBnoAC.agsub <- mscD8DBunkBnoAC.agsub[SCA_C!="G" & SCB_C!="G"]

    #mscACvsrest_AW.ag <- rbind(mscACvsrest.ag, mscACvsrest_POBC, mscD8DBunkBnoAC.agsub)
    mscACvsrest_AW.ag <- rbind(totalibsag, totalibsagPO, mscD8DBunkBnoAC.agsub)
    #mscACvsrest_AW.ag <- rbind(totalibsag, totalibsagPO)


    mscACvsrest_AW.ag$SCcompare <- paste(mscACvsrest_AW.ag$SCA_C,mscACvsrest_AW.ag$SCB_C,sep="_")

    mscACvsrest_AW.ag$ACvspond <- ifelse(mscACvsrest_AW.ag$SCA_C=="C" & mscACvsrest_AW.ag$SCB_C=="G", "C_Obtusa", ifelse(
      mscACvsrest_AW.ag$SCA_C=="C" & mscACvsrest_AW.ag$SCB_C=="P", "C_Pulicaria", mscACvsrest_AW.ag$ACvspond))

    mscACvsrest_AW.ag$ACvspond <- ifelse(mscACvsrest_AW.ag$ACvspond=="DBunk_D8", "D8_DBunk", mscACvsrest_AW.ag$ACvspond)

    mscACvsrest_AW.ag$ACvspond <- factor(mscACvsrest_AW.ag$ACvspond, levels=c("A_D8DBunk_C_D8DBunk",
      "D8_D8", "DBunk_DBunk", "D8_DBunk",
      "A_D10", "A_W1", "A_W6", "A_pulicaria", "A_obtusa", "C_D10", "C_W1", "C_W6", "C_Pulicaria", "C_Obtusa"))

    #mscACvsrest_AW.ag$SCcompare <- factor(mscACvsrest_AW.ag$SCcompare, levels=c("A_C", "A_D", "A_AF", "A_OO_Fall_2016_D10_41",
    #  "C_D", "C_AF", "C_OO_Fall_2016_D10_41", "A_OO_Spring_2016_W1_1.1", "A_OO_Spring_2016_W6_6.1", "A_OO_Spring_2016_W6_6.3",
    #  "C_OO_Spring_2016_W1_1.1", "C_OO_Spring_2016_W6_6.1", "C_OO_Spring_2016_W6_6.3", "A_P", "C_P", "A_G", "C_G"))

    mscACvsrest_AW.ag$colortype <- ifelse(mscACvsrest_AW.ag$ACvspond=="A_D8DBunk_C_D8DBunk", "AvsC",
      ifelse(mscACvsrest_AW.ag$ACvspond=="D8_D8" | mscACvsrest_AW.ag$ACvspond=="D8_DBunk" |
      mscACvsrest_AW.ag$ACvspond=="DBunk_DBunk", "D8_DBunk", ifelse(mscACvsrest_AW.ag$ACvspond=="A_D10" |
      mscACvsrest_AW.ag$ACvspond=="A_W1" | mscACvsrest_AW.ag$ACvspond=="A_W6" |
      mscACvsrest_AW.ag$ACvspond=="A_pulicaria" | mscACvsrest_AW.ag$ACvspond=="A_obtusa", "AvsOther",
      ifelse(mscACvsrest_AW.ag$ACvspond=="C_D10" | mscACvsrest_AW.ag$ACvspond=="C_W1" |
      mscACvsrest_AW.ag$ACvspond=="C_W6" | mscACvsrest_AW.ag$ACvspond=="C_Pulicaria" |
      mscACvsrest_AW.ag$ACvspond=="C_Obtusa", "CvsOther", "NA"))))

    mscACvsrest_AW.ag$colortype <- factor(mscACvsrest_AW.ag$colortype, levels=c("AvsC",
      "D8_DBunk", "AvsOther", "CvsOther"))

    #ggplot(data=mscACvsrest_AW.ag, aes(x=SCcompare, y=meanIBS, group=SCcompare, color=colortype)) + geom_boxplot()

    allbox <- ggplot(data=mscACvsrest_AW.ag, aes(x=ACvspond, y=meanIBS, group=ACvspond, color=colortype)) + geom_boxplot() +
      theme(axis.text.x = element_text(angle = 90, hjust = 1))
    allboxnoD8DBunk <- ggplot(data=mscACvsrest_AW.ag[colortype!="D8_DBunk"],
      aes(x=ACvspond, y=meanIBS, group=ACvspond, color=colortype)) + geom_boxplot() +
      theme(axis.text.x = element_text(angle = 90, hjust = 1))

    ggsave(allbox, file="IBSboxwhiskerall_20200524.pdf")
    ggsave(allboxnoD8DBunk, file="IBSboxwhiskernoD8DBunk_20200524.pdf")


    ggplot(data=mscACvsrest_AW.ag[ACvspond=="A_pulicaria" | ACvspond=="A_obtusa" |
      ACvspond=="C_Pulicaria" | ACvspond=="C_Obtusa" | ACvspond=="A_D8DBunk_C_D8DBunk"],
      aes(x=as.factor(window), y=meanIBS, group=ACvspond, color=ACvspond)) + geom_line() + facet_wrap(~chr, scales="free_x")

    tmp <- mscACvsrest_AW.ag[ACvspond=="A_pulicaria" | ACvspond=="A_obtusa" |
      ACvspond=="C_Pulicaria" | ACvspond=="C_Obtusa" | ACvspond=="A_D8DBunk_C_D8DBunk"]

      ggplot(data=tmp[chr=="Scaffold_6786_HRSCAF_7541" & window > 5250 & window < 5430],
        aes(x=as.factor(window), y=meanIBS, color=ACvspond)) + geom_point() + facet_wrap(~chr, scales="free_x")


    mscACvsrest_AW.ag <- mscACvsrest_AW.ag[window > 10000]

    ggplot() + geom_line(data=mscACvsrest_AW.ag[SCA_C=="A" & SCB_C=="OO_Spring_2016_W6_6.1"], aes(x=as.factor(window), y=meanIBS,
        group=SCB_C, color="AvsW6"), alpha=0.5) +
      geom_line(data=mscACvsrest_AW.ag[SCA_C=="A" & SCB_C=="OO_Spring_2016_W6_6.1"], aes(x=as.factor(window), y=meanIBS-2*sd_IBS,
          group=SCB_C, color="AvsW6"), alpha=0.5, linetype="dotted") +
      geom_line(data=mscACvsrest_AW.ag[SCA_C=="A" & SCB_C=="OO_Spring_2016_W6_6.1"], aes(x=as.factor(window), y=meanIBS+2*sd_IBS,
          group=SCB_C, color="AvsW6"), alpha=0.5, linetype="dotted") +
      geom_line(data=mscACvsrest_AW.ag[SCA_C=="A" & SCB_C=="OO_Spring_2016_W6_6.3"], aes(x=as.factor(window), y=meanIBS,
          group=SCB_C, color="AvsW6"), alpha=0.5) +
      geom_line(data=mscACvsrest_AW.ag[SCA_C=="A" & SCB_C=="OO_Spring_2016_W6_6.3"], aes(x=as.factor(window), y=meanIBS-2*sd_IBS,
          group=SCB_C, color="AvsW6"), alpha=0.5, linetype="dotted") +
      geom_line(data=mscACvsrest_AW.ag[SCA_C=="A" & SCB_C=="OO_Spring_2016_W6_6.3"], aes(x=as.factor(window), y=meanIBS+2*sd_IBS,
          group=SCB_C, color="AvsW6"), alpha=0.5, linetype="dotted") +
      geom_line(data=mscACvsrest_AW.ag[SCA_C=="A" & SCB_C=="OO_Spring_2016_W1_1.1"], aes(x=as.factor(window), y=meanIBS,
          group=SCB_C, color="AvsW1"), alpha=0.5) +
      geom_line(data=mscACvsrest_AW.ag[SCA_C=="A" & SCB_C=="OO_Spring_2016_W1_1.1"], aes(x=as.factor(window), y=meanIBS-2*sd_IBS,
          group=SCB_C, color="AvsW1"), alpha=0.5, linetype="dotted") +
      geom_line(data=mscACvsrest_AW.ag[SCA_C=="A" & SCB_C=="OO_Spring_2016_W1_1.1"], aes(x=as.factor(window), y=meanIBS+2*sd_IBS,
          group=SCB_C, color="AvsW1"), alpha=0.5, linetype="dotted") +
      geom_line(data=mscACvsrest_AW.ag[SCA_C=="A" & SCB_C=="D"], aes(x=as.factor(window), y=meanIBS,
          group=SCB_C, color="AvsD10"), alpha=0.5) +
      geom_line(data=mscACvsrest_AW.ag[SCA_C=="A" & SCB_C=="D"], aes(x=as.factor(window), y=meanIBS-2*sd_IBS,
          group=SCB_C, color="AvsD10"), alpha=0.5, linetype="dotted") +
      geom_line(data=mscACvsrest_AW.ag[SCA_C=="A" & SCB_C=="D"], aes(x=as.factor(window), y=meanIBS+2*sd_IBS,
          group=SCB_C, color="AvsD10"), alpha=0.5, linetype="dotted") +
      geom_line(data=mscACvsrest_AW.ag[SCA_C=="A" & SCB_C=="AF"], aes(x=as.factor(window), y=meanIBS,
          group=SCB_C, color="AvsD10"), alpha=0.5) +
      geom_line(data=mscACvsrest_AW.ag[SCA_C=="A" & SCB_C=="AF"], aes(x=as.factor(window), y=meanIBS-2*sd_IBS,
          group=SCB_C, color="AvsD10"), alpha=0.5, linetype="dotted") +
      geom_line(data=mscACvsrest_AW.ag[SCA_C=="A" & SCB_C=="AF"], aes(x=as.factor(window), y=meanIBS+2*sd_IBS,
          group=SCB_C, color="AvsD10"), alpha=0.5, linetype="dotted") +
      geom_line(data=mscACvsrest_AW.ag[SCA_C=="A" & SCB_C=="OO_Fall_2016_D10_41"], aes(x=as.factor(window), y=meanIBS,
          group=SCB_C, color="AvsD10"), alpha=0.5) +
      geom_line(data=mscACvsrest_AW.ag[SCA_C=="A" & SCB_C=="OO_Fall_2016_D10_41"], aes(x=as.factor(window), y=meanIBS-2*sd_IBS,
          group=SCB_C, color="AvsD10"), alpha=0.5, linetype="dotted") +
      geom_line(data=mscACvsrest_AW.ag[SCA_C=="A" & SCB_C=="OO_Fall_2016_D10_41"], aes(x=as.factor(window), y=meanIBS+2*sd_IBS,
          group=SCB_C, color="AvsD10"), alpha=0.5, linetype="dotted") +
            geom_line(data=mscACvsrest_AW.ag[SCA_C=="C" & SCB_C=="OO_Spring_2016_W6_6.1"], aes(x=as.factor(window), y=meanIBS,
                group=SCB_C, color="CvsW6"), alpha=0.5) +
              geom_line(data=mscACvsrest_AW.ag[SCA_C=="C" & SCB_C=="OO_Spring_2016_W6_6.1"], aes(x=as.factor(window), y=meanIBS-2*sd_IBS,
                  group=SCB_C, color="CvsW6"), alpha=0.5, linetype="dotted") +
              geom_line(data=mscACvsrest_AW.ag[SCA_C=="C" & SCB_C=="OO_Spring_2016_W6_6.1"], aes(x=as.factor(window), y=meanIBS+2*sd_IBS,
                  group=SCB_C, color="CvsW6"), alpha=0.5, linetype="dotted") +
              geom_line(data=mscACvsrest_AW.ag[SCA_C=="C" & SCB_C=="OO_Spring_2016_W6_6.3"], aes(x=as.factor(window), y=meanIBS,
                  group=SCB_C, color="CvsW6"), alpha=0.5) +
              geom_line(data=mscACvsrest_AW.ag[SCA_C=="C" & SCB_C=="OO_Spring_2016_W6_6.3"], aes(x=as.factor(window), y=meanIBS-2*sd_IBS,
                  group=SCB_C, color="CvsW6"), alpha=0.5, linetype="dotted") +
              geom_line(data=mscACvsrest_AW.ag[SCA_C=="C" & SCB_C=="OO_Spring_2016_W6_6.3"], aes(x=as.factor(window), y=meanIBS+2*sd_IBS,
                  group=SCB_C, color="CvsW6"), alpha=0.5, linetype="dotted") +
              geom_line(data=mscACvsrest_AW.ag[SCA_C=="C" & SCB_C=="OO_Spring_2016_W1_1.1"], aes(x=as.factor(window), y=meanIBS,
                  group=SCB_C, color="CvsW1"), alpha=0.5) +
              geom_line(data=mscACvsrest_AW.ag[SCA_C=="C" & SCB_C=="OO_Spring_2016_W1_1.1"], aes(x=as.factor(window), y=meanIBS-2*sd_IBS,
                  group=SCB_C, color="CvsW1"), alpha=0.5, linetype="dotted") +
              geom_line(data=mscACvsrest_AW.ag[SCA_C=="C" & SCB_C=="OO_Spring_2016_W1_1.1"], aes(x=as.factor(window), y=meanIBS+2*sd_IBS,
                  group=SCB_C, color="CvsW1"), alpha=0.5, linetype="dotted") +
              geom_line(data=mscACvsrest_AW.ag[SCA_C=="C" & SCB_C=="D"], aes(x=as.factor(window), y=meanIBS,
                  group=SCB_C, color="CvsD10"), alpha=0.5) +
              geom_line(data=mscACvsrest_AW.ag[SCA_C=="C" & SCB_C=="D"], aes(x=as.factor(window), y=meanIBS-2*sd_IBS,
                  group=SCB_C, color="CvsD10"), alpha=0.5, linetype="dotted") +
              geom_line(data=mscACvsrest_AW.ag[SCA_C=="C" & SCB_C=="D"], aes(x=as.factor(window), y=meanIBS+2*sd_IBS,
                  group=SCB_C, color="CvsD10"), alpha=0.5, linetype="dotted") +
              geom_line(data=mscACvsrest_AW.ag[SCA_C=="C" & SCB_C=="AF"], aes(x=as.factor(window), y=meanIBS,
                  group=SCB_C, color="CvsD10"), alpha=0.5) +
              geom_line(data=mscACvsrest_AW.ag[SCA_C=="C" & SCB_C=="AF"], aes(x=as.factor(window), y=meanIBS-2*sd_IBS,
                  group=SCB_C, color="CvsD10"), alpha=0.5, linetype="dotted") +
              geom_line(data=mscACvsrest_AW.ag[SCA_C=="C" & SCB_C=="AF"], aes(x=as.factor(window), y=meanIBS+2*sd_IBS,
                  group=SCB_C, color="CvsD10"), alpha=0.5, linetype="dotted") +
              geom_line(data=mscACvsrest_AW.ag[SCA_C=="C" & SCB_C=="OO_Fall_2016_D10_41"], aes(x=as.factor(window), y=meanIBS,
                  group=SCB_C, color="CvsD10"), alpha=0.5) +
              geom_line(data=mscACvsrest_AW.ag[SCA_C=="C" & SCB_C=="OO_Fall_2016_D10_41"], aes(x=as.factor(window), y=meanIBS-2*sd_IBS,
                  group=SCB_C, color="CvsD10"), alpha=0.5, linetype="dotted") +
              geom_line(data=mscACvsrest_AW.ag[SCA_C=="C" & SCB_C=="OO_Fall_2016_D10_41"], aes(x=as.factor(window), y=meanIBS+2*sd_IBS,
                  group=SCB_C, color="CvsD10"), alpha=0.5, linetype="dotted") +
              geom_line(data=mscACvsrest_AW.ag[SCA_C=="C" & SCB_C=="P"], aes(x=as.factor(window), y=meanIBS,
                  group=SCB_C, color="CvsPulicaria"), alpha=0.5) +
              geom_line(data=mscACvsrest_AW.ag[SCA_C=="C" & SCB_C=="P"], aes(x=as.factor(window), y=meanIBS-2*sd_IBS,
                  group=SCB_C, color="CvsPulicaria"), alpha=0.5, linetype="dotted") +
              geom_line(data=mscACvsrest_AW.ag[SCA_C=="C" & SCB_C=="P"], aes(x=as.factor(window), y=meanIBS+2*sd_IBS,
                  group=SCB_C, color="CvsPulicaria"), alpha=0.5, linetype="dotted") +
              geom_line(data=mscACvsrest_AW.ag[SCA_C=="C" & SCB_C=="G"], aes(x=as.factor(window), y=meanIBS,
                  group=SCB_C, color="CvsObtusa"), alpha=0.5) +
              geom_line(data=mscACvsrest_AW.ag[SCA_C=="C" & SCB_C=="G"], aes(x=as.factor(window), y=meanIBS-2*sd_IBS,
                  group=SCB_C, color="CvsObtusa"), alpha=0.5, linetype="dotted") +
              geom_line(data=mscACvsrest_AW.ag[SCA_C=="C" & SCB_C=="G"], aes(x=as.factor(window), y=meanIBS+2*sd_IBS,
                  group=SCB_C, color="CvsObtusa"), alpha=0.5, linetype="dotted") +
              geom_line(data=mscACvsrest_AW.ag[SCA_C=="A" & SCB_C=="G"], aes(x=as.factor(window), y=meanIBS,
                  group=SCB_C, color="AvsObtusa"), alpha=0.5) +
              geom_line(data=mscACvsrest_AW.ag[SCA_C=="A" & SCB_C=="G"], aes(x=as.factor(window), y=meanIBS-2*sd_IBS,
                  group=SCB_C, color="AvsObtusa"), alpha=0.5, linetype="dotted") +
              geom_line(data=mscACvsrest_AW.ag[SCA_C=="A" & SCB_C=="G"], aes(x=as.factor(window), y=meanIBS+2*sd_IBS,
                  group=SCB_C, color="AvsObtusa"), alpha=0.5, linetype="dotted") +
              geom_line(data=mscACvsrest_AW.ag[SCA_C=="A" & SCB_C=="P"], aes(x=as.factor(window), y=meanIBS,
                  group=SCB_C, color="AvsPulicaria"), alpha=0.5) +
              geom_line(data=mscACvsrest_AW.ag[SCA_C=="A" & SCB_C=="P"], aes(x=as.factor(window), y=meanIBS-2*sd_IBS,
                  group=SCB_C, color="AvsPulicaria"), alpha=0.5, linetype="dotted") +
              geom_line(data=mscACvsrest_AW.ag[SCA_C=="A" & SCB_C=="P"], aes(x=as.factor(window), y=meanIBS+2*sd_IBS,
                  group=SCB_C, color="AvsPulicaria"), alpha=0.5, linetype="dotted") +
                  geom_line(data=mscACvsrest_AW.ag[SCB_C=="C"], aes(x=as.factor(window), y=meanIBS, group=SCB_C, color="AvsC"), size=1) +
                      geom_line(data=mscACvsrest_AW.ag[SCB_C=="C"], aes(x=as.factor(window), y=meanIBS-2*sd_IBS, group=SCB_C,
                        color="AvsC"), linetype="dotted") +
                      geom_line(data=mscACvsrest_AW.ag[SCB_C=="C"], aes(x=as.factor(window), y=meanIBS+2*sd_IBS, group=SCB_C,
                        color="AvsC"), linetype="dotted")


          ACvsOB <-              ggplot() + geom_line(data=mscACvsrest_AW.ag[SCA_C=="C" & SCB_C=="P"], aes(x=as.factor(window), y=meanIBS,
                                      group=SCB_C, color="CvsPulicaria"), alpha=0.5) +
                                  geom_line(data=mscACvsrest_AW.ag[SCA_C=="C" & SCB_C=="P"], aes(x=as.factor(window), y=meanIBS-2*sd_IBS,
                                      group=SCB_C, color="CvsPulicaria"), alpha=0.5, linetype="dotted") +
                                  geom_line(data=mscACvsrest_AW.ag[SCA_C=="C" & SCB_C=="P"], aes(x=as.factor(window), y=meanIBS+2*sd_IBS,
                                      group=SCB_C, color="CvsPulicaria"), alpha=0.5, linetype="dotted") +
                                  geom_line(data=mscACvsrest_AW.ag[SCA_C=="C" & SCB_C=="G"], aes(x=as.factor(window), y=meanIBS,
                                      group=SCB_C, color="CvsObtusa"), alpha=0.5) +
                                  geom_line(data=mscACvsrest_AW.ag[SCA_C=="C" & SCB_C=="G"], aes(x=as.factor(window), y=meanIBS-2*sd_IBS,
                                      group=SCB_C, color="CvsObtusa"), alpha=0.5, linetype="dotted") +
                                  geom_line(data=mscACvsrest_AW.ag[SCA_C=="C" & SCB_C=="G"], aes(x=as.factor(window), y=meanIBS+2*sd_IBS,
                                      group=SCB_C, color="CvsObtusa"), alpha=0.5, linetype="dotted") +
                                  geom_line(data=mscACvsrest_AW.ag[SCA_C=="A" & SCB_C=="G"], aes(x=as.factor(window), y=meanIBS,
                                      group=SCB_C, color="AvsObtusa"), alpha=0.5) +
                                  geom_line(data=mscACvsrest_AW.ag[SCA_C=="A" & SCB_C=="G"], aes(x=as.factor(window), y=meanIBS-2*sd_IBS,
                                      group=SCB_C, color="AvsObtusa"), alpha=0.5, linetype="dotted") +
                                  geom_line(data=mscACvsrest_AW.ag[SCA_C=="A" & SCB_C=="G"], aes(x=as.factor(window), y=meanIBS+2*sd_IBS,
                                      group=SCB_C, color="AvsObtusa"), alpha=0.5, linetype="dotted") +
                                  geom_line(data=mscACvsrest_AW.ag[SCA_C=="A" & SCB_C=="P"], aes(x=as.factor(window), y=meanIBS,
                                      group=SCB_C, color="AvsPulicaria"), alpha=0.5) +
                                  geom_line(data=mscACvsrest_AW.ag[SCA_C=="A" & SCB_C=="P"], aes(x=as.factor(window), y=meanIBS-2*sd_IBS,
                                      group=SCB_C, color="AvsPulicaria"), alpha=0.5, linetype="dotted") +
                                  geom_line(data=mscACvsrest_AW.ag[SCA_C=="A" & SCB_C=="P"], aes(x=as.factor(window), y=meanIBS+2*sd_IBS,
                                      group=SCB_C, color="AvsPulicaria"), alpha=0.5, linetype="dotted") +
                                      geom_line(data=mscACvsrest_AW.ag[SCB_C=="C"], aes(x=as.factor(window), y=meanIBS, group=SCB_C, color="AvsC"), size=1) +
                                          geom_line(data=mscACvsrest_AW.ag[SCB_C=="C"], aes(x=as.factor(window), y=meanIBS-2*sd_IBS, group=SCB_C,
                                            color="AvsC"), linetype="dotted") +
                                          geom_line(data=mscACvsrest_AW.ag[SCB_C=="C"], aes(x=as.factor(window), y=meanIBS+2*sd_IBS, group=SCB_C,
                                            color="AvsC"), linetype="dotted") + facet_wrap(~mscACvsrest_AW.ag$chr)


                      ggplot() + geom_line(data=mscACvsrest_AW.ag[SCA_C=="C" & SCB_C=="P"], aes(x=as.factor(window), y=meanIBS,
                              group=SCB_C, color="CvsPulicaria"), alpha=0.5) +
                      geom_line(data=mscACvsrest_AW.ag[SCA_C=="C" & SCB_C=="P"], aes(x=as.factor(window), y=meanIBS-2*sd_IBS,
                              group=SCB_C, color="CvsPulicaria"), alpha=0.5, linetype="dotted") +
                      geom_line(data=mscACvsrest_AW.ag[SCA_C=="C" & SCB_C=="P"], aes(x=as.factor(window), y=meanIBS+2*sd_IBS,
                              group=SCB_C, color="CvsPulicaria"), alpha=0.5, linetype="dotted") + facet_wrap(~chr, scales="free_x")

      mscACvsrest_AW.agPO <- mscACvsrest_AW.ag[SCB_C=="P" | SCB_C=="G" | SCB_C=="C"]
      mscACvsrest_AW.agPO$ACvspond <- ifelse(mscACvsrest_AW.agPO$SCA_C=="C" & mscACvsrest_AW.agPO$SCB_C=="G", "C_Obtusa", ifelse(
        mscACvsrest_AW.agPO$SCA_C=="C" & mscACvsrest_AW.agPO$SCB_C=="P", "C_Pulicaria", ifelse(mscACvsrest_AW.agPO$SCA_C=="A" &
        mscACvsrest_AW.agPO$SCB_C=="G", "A_Obtusa", ifelse(mscACvsrest_AW.agPO$SCA_C=="A" &
        mscACvsrest_AW.agPO$SCB_C=="P", "A_Pulicaria", mscACvsrest_AW.agPO$ACvspond))))


          ggplot(data=mscACvsrest_AW.agPO, aes(x=as.factor(window), y=meanIBS, group=ACvspond, color=ACvspond)) + geom_line() + facet_wrap(~chr, scales="free_x")
          ggplot(data=mscACvsrest_AW.ag, aes(x=as.factor(window), y=meanIBS, group=SCcompare, color=ACvspond, group=ACvspond)) + geom_line() + facet_wrap(~chr, scales="free_x")

                        ggplot() + geom_line(data=mscACvsrest_AW.ag[SCA_C=="A" & SCB_C=="OO_Spring_2016_W6_6.1"], aes(x=as.factor(window), y=meanIBS,
                            group=SCB_C, color="ACvsW6"), alpha=0.5) +
                          geom_line(data=mscACvsrest_AW.ag[SCA_C=="A" & SCB_C=="OO_Spring_2016_W6_6.1"], aes(x=as.factor(window), y=meanIBS-2*sd_IBS,
                              group=SCB_C, color="ACvsW6"), alpha=0.5, linetype="dotted") +
                          geom_line(data=mscACvsrest_AW.ag[SCA_C=="A" & SCB_C=="OO_Spring_2016_W6_6.1"], aes(x=as.factor(window), y=meanIBS+2*sd_IBS,
                              group=SCB_C, color="ACvsW6"), alpha=0.5, linetype="dotted") +
                          geom_line(data=mscACvsrest_AW.ag[SCA_C=="A" & SCB_C=="OO_Spring_2016_W6_6.3"], aes(x=as.factor(window), y=meanIBS,
                              group=SCB_C, color="ACvsW6"), alpha=0.5) +
                          geom_line(data=mscACvsrest_AW.ag[SCA_C=="A" & SCB_C=="OO_Spring_2016_W6_6.3"], aes(x=as.factor(window), y=meanIBS-2*sd_IBS,
                              group=SCB_C, color="ACvsW6"), alpha=0.5, linetype="dotted") +
                          geom_line(data=mscACvsrest_AW.ag[SCA_C=="A" & SCB_C=="OO_Spring_2016_W6_6.3"], aes(x=as.factor(window), y=meanIBS+2*sd_IBS,
                              group=SCB_C, color="ACvsW6"), alpha=0.5, linetype="dotted") +
                          geom_line(data=mscACvsrest_AW.ag[SCA_C=="A" & SCB_C=="OO_Spring_2016_W1_1.1"], aes(x=as.factor(window), y=meanIBS,
                              group=SCB_C, color="ACvsW1"), alpha=0.5) +
                          geom_line(data=mscACvsrest_AW.ag[SCA_C=="A" & SCB_C=="OO_Spring_2016_W1_1.1"], aes(x=as.factor(window), y=meanIBS-2*sd_IBS,
                              group=SCB_C, color="ACvsW1"), alpha=0.5, linetype="dotted") +
                          geom_line(data=mscACvsrest_AW.ag[SCA_C=="A" & SCB_C=="OO_Spring_2016_W1_1.1"], aes(x=as.factor(window), y=meanIBS+2*sd_IBS,
                              group=SCB_C, color="ACvsW1"), alpha=0.5, linetype="dotted") +
                          geom_line(data=mscACvsrest_AW.ag[SCA_C=="A" & SCB_C=="D"], aes(x=as.factor(window), y=meanIBS,
                              group=SCB_C, color="ACvsD10"), alpha=0.5) +
                          geom_line(data=mscACvsrest_AW.ag[SCA_C=="A" & SCB_C=="D"], aes(x=as.factor(window), y=meanIBS-2*sd_IBS,
                              group=SCB_C, color="ACvsD10"), alpha=0.5, linetype="dotted") +
                          geom_line(data=mscACvsrest_AW.ag[SCA_C=="A" & SCB_C=="D"], aes(x=as.factor(window), y=meanIBS+2*sd_IBS,
                              group=SCB_C, color="ACvsD10"), alpha=0.5, linetype="dotted") +
                          geom_line(data=mscACvsrest_AW.ag[SCA_C=="A" & SCB_C=="AF"], aes(x=as.factor(window), y=meanIBS,
                              group=SCB_C, color="ACvsD10"), alpha=0.5) +
                          geom_line(data=mscACvsrest_AW.ag[SCA_C=="A" & SCB_C=="AF"], aes(x=as.factor(window), y=meanIBS-2*sd_IBS,
                              group=SCB_C, color="ACvsD10"), alpha=0.5, linetype="dotted") +
                          geom_line(data=mscACvsrest_AW.ag[SCA_C=="A" & SCB_C=="AF"], aes(x=as.factor(window), y=meanIBS+2*sd_IBS,
                              group=SCB_C, color="ACvsD10"), alpha=0.5, linetype="dotted") +
                          geom_line(data=mscACvsrest_AW.ag[SCA_C=="A" & SCB_C=="OO_Fall_2016_D10_41"], aes(x=as.factor(window), y=meanIBS,
                              group=SCB_C, color="ACvsD10"), alpha=0.5) +
                          geom_line(data=mscACvsrest_AW.ag[SCA_C=="A" & SCB_C=="OO_Fall_2016_D10_41"], aes(x=as.factor(window), y=meanIBS-2*sd_IBS,
                              group=SCB_C, color="ACvsD10"), alpha=0.5, linetype="dotted") +
                          geom_line(data=mscACvsrest_AW.ag[SCA_C=="A" & SCB_C=="OO_Fall_2016_D10_41"], aes(x=as.factor(window), y=meanIBS+2*sd_IBS,
                              group=SCB_C, color="ACvsD10"), alpha=0.5, linetype="dotted") +
                                geom_line(data=mscACvsrest_AW.ag[SCA_C=="C" & SCB_C=="OO_Spring_2016_W6_6.1"], aes(x=as.factor(window), y=meanIBS,
                                    group=SCB_C, color="ACvsW6"), alpha=0.5) +
                                  geom_line(data=mscACvsrest_AW.ag[SCA_C=="C" & SCB_C=="OO_Spring_2016_W6_6.1"], aes(x=as.factor(window), y=meanIBS-2*sd_IBS,
                                      group=SCB_C, color="ACvsW6"), alpha=0.5, linetype="dotted") +
                                  geom_line(data=mscACvsrest_AW.ag[SCA_C=="C" & SCB_C=="OO_Spring_2016_W6_6.1"], aes(x=as.factor(window), y=meanIBS+2*sd_IBS,
                                      group=SCB_C, color="ACvsW6"), alpha=0.5, linetype="dotted") +
                                  geom_line(data=mscACvsrest_AW.ag[SCA_C=="C" & SCB_C=="OO_Spring_2016_W6_6.3"], aes(x=as.factor(window), y=meanIBS,
                                      group=SCB_C, color="ACvsW6"), alpha=0.5) +
                                  geom_line(data=mscACvsrest_AW.ag[SCA_C=="C" & SCB_C=="OO_Spring_2016_W6_6.3"], aes(x=as.factor(window), y=meanIBS-2*sd_IBS,
                                      group=SCB_C, color="ACvsW6"), alpha=0.5, linetype="dotted") +
                                  geom_line(data=mscACvsrest_AW.ag[SCA_C=="C" & SCB_C=="OO_Spring_2016_W6_6.3"], aes(x=as.factor(window), y=meanIBS+2*sd_IBS,
                                      group=SCB_C, color="ACvsW6"), alpha=0.5, linetype="dotted") +
                                  geom_line(data=mscACvsrest_AW.ag[SCA_C=="C" & SCB_C=="OO_Spring_2016_W1_1.1"], aes(x=as.factor(window), y=meanIBS,
                                      group=SCB_C, color="ACvsW1"), alpha=0.5) +
                                  geom_line(data=mscACvsrest_AW.ag[SCA_C=="C" & SCB_C=="OO_Spring_2016_W1_1.1"], aes(x=as.factor(window), y=meanIBS-2*sd_IBS,
                                      group=SCB_C, color="ACvsW1"), alpha=0.5, linetype="dotted") +
                                  geom_line(data=mscACvsrest_AW.ag[SCA_C=="C" & SCB_C=="OO_Spring_2016_W1_1.1"], aes(x=as.factor(window), y=meanIBS+2*sd_IBS,
                                      group=SCB_C, color="ACvsW1"), alpha=0.5, linetype="dotted") +
                                  geom_line(data=mscACvsrest_AW.ag[SCA_C=="C" & SCB_C=="D"], aes(x=as.factor(window), y=meanIBS,
                                      group=SCB_C, color="ACvsD10"), alpha=0.5) +
                                  geom_line(data=mscACvsrest_AW.ag[SCA_C=="C" & SCB_C=="D"], aes(x=as.factor(window), y=meanIBS-2*sd_IBS,
                                      group=SCB_C, color="ACvsD10"), alpha=0.5, linetype="dotted") +
                                  geom_line(data=mscACvsrest_AW.ag[SCA_C=="C" & SCB_C=="D"], aes(x=as.factor(window), y=meanIBS+2*sd_IBS,
                                      group=SCB_C, color="ACvsD10"), alpha=0.5, linetype="dotted") +
                                  geom_line(data=mscACvsrest_AW.ag[SCA_C=="C" & SCB_C=="AF"], aes(x=as.factor(window), y=meanIBS,
                                      group=SCB_C, color="ACvsD10"), alpha=0.5) +
                                  geom_line(data=mscACvsrest_AW.ag[SCA_C=="C" & SCB_C=="AF"], aes(x=as.factor(window), y=meanIBS-2*sd_IBS,
                                      group=SCB_C, color="ACvsD10"), alpha=0.5, linetype="dotted") +
                                  geom_line(data=mscACvsrest_AW.ag[SCA_C=="C" & SCB_C=="AF"], aes(x=as.factor(window), y=meanIBS+2*sd_IBS,
                                      group=SCB_C, color="ACvsD10"), alpha=0.5, linetype="dotted") +
                                  geom_line(data=mscACvsrest_AW.ag[SCA_C=="C" & SCB_C=="OO_Fall_2016_D10_41"], aes(x=as.factor(window), y=meanIBS,
                                      group=SCB_C, color="ACvsD10"), alpha=0.5) +
                                  geom_line(data=mscACvsrest_AW.ag[SCA_C=="C" & SCB_C=="OO_Fall_2016_D10_41"], aes(x=as.factor(window), y=meanIBS-2*sd_IBS,
                                      group=SCB_C, color="ACvsD10"), alpha=0.5, linetype="dotted") +
                                  geom_line(data=mscACvsrest_AW.ag[SCA_C=="C" & SCB_C=="OO_Fall_2016_D10_41"], aes(x=as.factor(window), y=meanIBS+2*sd_IBS,
                                      group=SCB_C, color="ACvsD10"), alpha=0.5, linetype="dotted") +
                                      geom_line(data=mscACvsrest_AW.ag[SCB_C=="C"], aes(x=as.factor(window), y=meanIBS, group=SCB_C, color="AvsC"), size=1) +
                                          geom_line(data=mscACvsrest_AW.ag[SCB_C=="C"], aes(x=as.factor(window), y=meanIBS-2*sd_IBS, group=SCB_C,
                                            color="AvsC"), linetype="dotted") +
                                          geom_line(data=mscACvsrest_AW.ag[SCB_C=="C"], aes(x=as.factor(window), y=meanIBS+2*sd_IBS, group=SCB_C,
                                            color="AvsC"), linetype="dotted")



    mscACvsrest_A.ag <- mscACvsrest_A[,list(meanIBS=mean(IBS), sd_IBS=sd(IBS)),
      list(window, chr, start, stop, SCcomp, speciesA, speciesB, popA, popB, SCA_C, SCB_C)]

    mscACvsrest_A.agW <- mscACvsrest_A.ag[popA=="W1" | popA=="W6" | popB=="W1" | popB=="W6"]
    mscACvsrest_A.agW$popcomp <- paste(mscACvsrest_A.agW$popA, mscACvsrest_A.agW$popB, sep="_")

  # First thing we want to do is compare AvsC to AvsW and CvsW, or AvsD10 and CvsD10, etc. Let's start with A and C vs W1 and W6
  # Let's make a file with just the W ponds and A and C clones, and remove DMud
    mscACvsrest.agW <- mscACvsrest.ag[popA=="W1" | popA=="W6" | popB=="W1" | popB=="W6"]
    mscACvsrest.agW <- mscACvsrest.agW[popA!="DMud" & popB!="DMud"]

    save(msc, file="m_IBSbyslidingwindow_subsetSC_1000000_100000_nosub_202003025_withsc.Rdata")

  mscwithinsc <- msc[SCA==SCB]
  save(mscwithinsc, file="m_IBSbyslidingwindow_subsetSC_1000000_100000_nosub_202003025_withsc_withinsc.Rdata")
  mscwithinscOO <- mscwithinsc[SCA=="OO"]
  save(mscwithinscOO, file="m_IBSbyslidingwindow_subsetSC_1000000_100000_nosub_202003025_withsc_OOcomparisons.Rdata")




  scsubA <- data.table(cloneA=sc$clone, medrdA=sc$medrd)
  scsubB <- data.table(cloneB=sc$clone, medrdB=sc$medrd)
  setkey(scsubB, cloneB)
  setkey(mscwithinsc, cloneB)
  m <- merge(mscwithinsc, scsubB)
  setkey(scsubA, cloneA)
  setkey(m, cloneA)
  m2 <- merge(m, scsubA)
  m2noOO <- m2[SCA!="OO"]

  m2noOO.ag <- m2noOO[,list(meanIBS=mean(IBS), sd_IBS=sd(IBS)),
    list(SCA, window, chr, start, stop)]

  m2noOO$clonecompare <- paste(m2noOO$cloneA,m2noOO$cloneB,sep="_")
  m2noOO.agbyclone <- m2noOO[,list(meanIBS=mean(IBS), sd_IBS=sd(IBS)),
    list(clonecompare, SCA, medrdA, medrdB)]





  #!/usr/bin/env Rscript

  ### libraries
    library(data.table)
    library(foreach)
    library(ggplot2)

  load("m_IBSbyslidingwindow_subsetSC_1000000_100000_nosub_202003025_withsc.Rdata")
  sc <- fread("/scratch/kbb7sh/Daphnia/MappingDecember2019/MapDec19PulexandObtusaC/CloneInfoFilePulexandObtusa_withmedrd_update20200324")

  mscbetweenpop <- msc[SCA!=SCB]

  mscbetweenpop$populationA <- ifelse(mscbetweenpop$populationA=="Dcat", "DCat", mscbetweenpop$populationA)
  mscbetweenpop$populationB <- ifelse(mscbetweenpop$populationB=="Dcat", "DCat", mscbetweenpop$populationB)

  mscbetweenpop$SCcompare <- paste(mscbetweenpop$SCA,mscbetweenpop$SCB, sep="_")
  mscbetweenpop$popcompare <- paste(mscbetweenpop$populationA,mscbetweenpop$populationB, sep="_")
  mscbetweenpop$SCpop <- paste(mscbetweenpop$SCcompare,mscbetweenpop$popcompare,sep="_")

  msc.ag <- mscbetweenpop[,list(meanIBS=mean(IBS), sd_IBS=sd(IBS)),
    list(SCpop, window, chr, start, stop)]

  save(msc.ag, file="m_IBSbyslidingwindow_subsetSC_1000000_100000_nosub_202003025_withsc_betweensc_agg")

  temp <- unlist(strsplit(as.character(msc.ag$SCpop), split="_"))
  mat <- matrix(temp, ncol=4, byrow=TRUE)
  matdat <- as.data.table(mat)
  msc.ag$SCcompare <- paste(matdat$V1,matdat$V2,sep="_")
  msc.ag$populationA <- matdat$V3
  msc.ag$populationB <- matdat$V4
  msc.ag$pondcompare <- paste(matdat$V3,matdat$V4,sep="_")

  msc.ag$pondcompare <- ifelse(msc.ag$pondcompare=="D8_D10", "D10_D8", msc.ag$pondcompare)
  msc.ag$pondcompare <- ifelse(msc.ag$pondcompare=="DBunk_D10", "D10_DBunk", msc.ag$pondcompare)
  msc.ag$pondcompare <- ifelse(msc.ag$pondcompare=="DCat_D10", "D10_DCat", msc.ag$pondcompare)
  msc.ag$pondcompare <- ifelse(msc.ag$pondcompare=="DBunk_D8", "D8_DBunk", msc.ag$pondcompare)
  msc.ag$pondcompare <- ifelse(msc.ag$pondcompare=="DCat_D8", "D8_DCat", msc.ag$pondcompare)
  msc.ag$pondcompare <- ifelse(msc.ag$pondcompare=="W1_D8", "D8_W1", msc.ag$pondcompare)
  msc.ag$pondcompare <- ifelse(msc.ag$pondcompare=="W6_D8", "D8_W6", msc.ag$pondcompare)
  msc.ag$pondcompare <- ifelse(msc.ag$pondcompare=="W1_DBunk", "DBunk_W1", msc.ag$pondcompare)
  msc.ag$pondcompare <- ifelse(msc.ag$pondcompare=="W6_DBunk", "DBunk_W6", msc.ag$pondcompare)

  msc.agsub <- msc.ag[populationA!="DOil" & populationA!="Dramp" & populationB!="DOil" & populationB!="Dramp" &
    populationA!="DMud" & populationA!="DLily" & populationB!="DMud" & populationB!="DLily"]

  msc.agsubAC <- msc.agsub[SCcompare=="A_C" | SCcompare=="C_A"]
  msc.agsubnoAC <- msc.agsub[SCcompare!="A_C" | SCcompare!="C_A"]

  msc.agponds <- msc.agsubnoAC[,list(meanIBS=mean(meanIBS), sd_IBS=sd(meanIBS)),
    list(pondcompare, window, chr, start, stop)]

  msc.agAC <- msc.agsubAC[,list(meanIBS=mean(meanIBS), sd_IBS=sd(sd_IBS)),
    list(window, chr, start, stop)]
  msc.agAC$pondcompare <- c("A_C")

  msc.ag2 <- rbind(msc.agAC, msc.agponds)

  msc.ag2$category <- ifelse(msc.ag2$pondcompare=="D8_DBunk" | msc.ag2$pondcompare=="D8_DCat" |
    msc.ag2$pondcompare=="DBunk_DCat", "D8surround", ifelse(msc.ag2$pondcompare=="D10_D8" |
    msc.ag2$pondcompare=="D10_DBunk" | msc.ag2$pondcompare=="D10_DCat", "D10vsD8Surround", ifelse(
    msc.ag2$pondcompare=="D8_W1" | msc.ag2$pondcompare=="D8_W6" |
    msc.ag2$pondcompare=="DBunk_W1" | msc.ag2$pondcompare=="DBunk_W6" |
    msc.ag2$pondcompare=="W1_DCat" | msc.ag2$pondcompare=="W6_DCat", "WvsD8Surround", ifelse(
    msc.ag2$pondcompare=="A_C", "zAvsB", ifelse(msc.ag2$pondcompare=="W1_D10" |
    msc.ag2$pondcompare=="W6_D10" | msc.ag2$pondcompare=="W6_W1", 6, "WithinPond")))))

    ggplot(data=msc.ag2[category!="6"], aes(x=as.factor(window), y=meanIBS, group=as.factor(pondcompare), color=as.factor(category))) + geom_line()
    ggplot(data=msc.ag2[category!="6" & category!="zAvsB"], aes(x=as.factor(window), y=sd_IBS, group=as.factor(pondcompare), color=as.factor(category))) + geom_line()

  msc.ag2$UCI <- msc.ag2$meanIBS+(2*msc.ag2$sd_IBS)

    ggplot() + geom_line(data=msc.ag2[pondcompare=="D8_D8"], aes(x=as.factor(window), y=meanIBS, group=as.factor(pondcompare))) +
      geom_line(data=msc.ag2[pondcompare=="D8_D8"], aes(x=as.factor(window), y=meanIBS+2*sd_IBS, group=as.factor(pondcompare), color="grey")) +
      geom_line(data=msc.ag2[pondcompare=="D8_D8"], aes(x=as.factor(window), y=meanIBS-2*sd_IBS, group=as.factor(pondcompare), color="grey")) +
      geom_line(data=msc.ag2[pondcompare=="A_C"], aes(x=as.factor(window), y=meanIBS, group=as.factor(pondcompare), color="blue"))

      ggplot() + geom_line(data=msc.ag2[pondcompare=="D8_DBunk"], aes(x=as.factor(window), y=meanIBS, group=as.factor(pondcompare))) +
        geom_line(data=msc.ag2[pondcompare=="D8_DBunk"], aes(x=as.factor(window), y=meanIBS+2*sd_IBS, group=as.factor(pondcompare), color="grey")) +
        geom_line(data=msc.ag2[pondcompare=="D8_DBunk"], aes(x=as.factor(window), y=meanIBS-2*sd_IBS, group=as.factor(pondcompare), color="grey")) +
        geom_line(data=msc.ag2[pondcompare=="A_C"], aes(x=as.factor(window), y=meanIBS, group=as.factor(pondcompare), color="blue"))

        ggplot() + geom_line(data=msc.ag2[pondcompare=="D10_D8"], aes(x=as.factor(window), y=meanIBS, group=as.factor(pondcompare))) +
          geom_line(data=msc.ag2[pondcompare=="D10_D8"], aes(x=as.factor(window), y=meanIBS+2*sd_IBS, group=as.factor(pondcompare), color="grey")) +
          geom_line(data=msc.ag2[pondcompare=="D10_D8"], aes(x=as.factor(window), y=meanIBS-2*sd_IBS, group=as.factor(pondcompare), color="grey")) +
          geom_line(data=msc.ag2[pondcompare=="A_C"], aes(x=as.factor(window), y=meanIBS, group=as.factor(pondcompare), color="blue"))


  #msc <- msc[populationA!="DOil" & populationA!="Dramp" & populationB!="DOil" & populationB!="Dramp"]

  msc$pondcompare <- paste(msc$populationA, msc$populationB, sep="_")
  msc$SCcompare <- paste(msc$SCA, msc$SCB, sep="_")

  msc$pondcompare <- str_replace(msc$pondcompare, "D8_D10", "D10_D8")
  msc$pondcompare <- str_replace(msc$pondcompare, "DBunk_D10", "D10_DBunk")
  msc$pondcompare <- str_replace(msc$pondcompare, "DCat_D10", "D10_DCat")
  msc$pondcompare <- str_replace(msc$pondcompare, "DBunk_D8", "D8_DBunk")
  msc$pondcompare <- str_replace(msc$pondcompare, "DCat_D8", "D8_DCat")
  msc$pondcompare <- str_replace(msc$pondcompare, "W1_D8", "D8_W1")
  msc$pondcompare <- str_replace(msc$pondcompare, "W6_D8", "D8_W6")
  msc$pondcompare <- str_replace(msc$pondcompare, "W1_DBunk", "DBunk_W1")
  msc$pondcompare <- str_replace(msc$pondcompare, "W6_DBunk", "DBunk_W6")

  save(msc, file="m_IBSbyslidingwindow_subsetSC_1000000_100000_nosub_202003025_withscsubpond.Rdata")



  msc.ag <- msc[,list(meanIBS=mean(distance), sd_IBS=sd(distance)),
    list(pondcompare, window, chr, start, stop)]
  ABsub <- data.table(pondcompare=c("A_C"), window=msc$window[msc$SCcompare=="A_C"],
    chr=msc$chr[msc$SCcompare=="A_C"], start=msc$start[msc$SCcompare=="A_C"],
    stop=msc$stop[msc$SCcompare=="A_C"], meanIBS=msc$distance[msc$SCcompare=="A_C"],
    sd_IBS=c("NA"))
  msc.ag2 <- rbind(msc.ag, ABsub)
  msc.ag2$category <- ifelse(msc.ag2$pondcompare=="D8_DBunk" | msc.ag2$pondcompare=="D8_DCat" |
    msc.ag2$pondcompare=="DBunk_DCat", "D8surround", ifelse(msc.ag2$pondcompare=="D10_D8" |
    msc.ag2$pondcompare=="D10_DBunk" | msc.ag2$pondcompare=="D10_DCat", "D10vsD8Surround", ifelse(
    msc.ag2$pondcompare=="D8_W1" | msc.ag2$pondcompare=="D8_W6" |
    msc.ag2$pondcompare=="DBunk_W1" | msc.ag2$pondcompare=="DBunk_W6" |
    msc.ag2$pondcompare=="W1_DCat" | msc.ag2$pondcompare=="W6_DCat", "WvsD8Surround", ifelse(
    msc.ag2$pondcompare=="A_C", "zAvsB", ifelse(msc.ag2$pondcompare=="W1_D10" |
    msc.ag2$pondcompare=="W6_D10" | msc.ag2$pondcompare=="W6_W1", 6, "WithinPond")))))
  ggplot(data=mscsubpondB, aes(x=as.factor(pondcompare), y=meanIBS, color=as.factor(withinpond))) + geom_beeswarm()
  ggplot(data=msc.ag2[category!="6"], aes(x=as.factor(window), y=meanIBS, group=as.factor(pondcompare), color=as.factor(category))) + geom_line()
  ggplot(data=msc.ag2[category!="6" & category!="zAvsB"], aes(x=as.factor(window), y=sd_IBS, group=as.factor(pondcompare), color=as.factor(category))) + geom_line()













  setkey(msc, pondcompare, SCcompare, window)
  msc.ag <- msc[,list(meanIBS = mean(distance)),
    list(pondcompare, SCcompare, window, chr, start, stop, populationA, populationB, SCA, SCB)]
  ggplot(data=mscsubpondB, aes(x=window, y=meanIBS, color=as.factor(withinpond))) + geom_point()
  ggplot(data=mscsubpondB[window>0 & window < 11], aes(x=as.factor(withinpond), y=meanIBS,
    color=as.factor(withinpond))) + geom_beeswarm() + facet_wrap(~window)
  mscsubpondB$windowwithin <- paste(mscsubpondB$window, mscsubpondB$withinpond, sep="_")
  ggplot(data=mscsubpondB, aes(x=windowwithin, y=meanIBS, color=as.factor(withinpond))) + geom_violin()
  mscsubpondB$A_C <- ifelse(mscsubpondB$SCcompare=="A_C" | mscsubpondB$SCcompare=="C_A", 1, 0)
  mscsubpondB$withinpondB <- ifelse(mscsubpondB$A_C==1, 2, ifelse(mscsubpondB$A_C==0 & mscsubpondB$withinpond==1, 1, 0))
  ggplot(data=mscsubpondB, aes(x=windowwithin, y=meanIBS, color=as.factor(withinpondB))) + geom_point()
  mscsubpondB$windowwithinB <- paste(mscsubpondB$window, mscsubpondB$withinpondB, sep="_")
  ggplot(data=mscsubpondB, aes(x=windowwithinB, y=meanIBS, color=as.factor(withinpondB))) + geom_point()
  ggplot(data=mscsubpondB[window < 60 & populationA!="D10" & populationB!="D10"], aes(x=windowwithinB, y=meanIBS, color=as.factor(withinpondB))) + geom_point()

  msc.ag$pondcompare <- str_replace(msc.ag$pondcompare, "D8_D10", "D10_D8")
  msc.ag$pondcompare <- str_replace(msc.ag$pondcompare, "DBunk_D10", "D10_DBunk")
  msc.ag$pondcompare <- str_replace(msc.ag$pondcompare, "DCat_D10", "D10_DCat")
  msc.ag$pondcompare <- str_replace(msc.ag$pondcompare, "DBunk_D8", "D8_DBunk")
  msc.ag$pondcompare <- str_replace(msc.ag$pondcompare, "DCat_D8", "D8_DCat")
  msc.ag$pondcompare <- str_replace(msc.ag$pondcompare, "DCat_DBunk", "DBunk_DCat")

  msc.ag2 <- msc.ag[,list(meanIBS=mean(meanIBS), sd_IBS=sd(meanIBS)),
    list(pondcompare, window, chr, start, stop, populationA, populationB)]

  mscsubpond <- msc.ag2[populationA=="D8" | populationA=="DBunk" | populationA=="DCat" | populationA=="D10"]
  mscsubpondB <- mscsubpond[populationB=="D8" | populationB=="DBunk" | populationB=="DCat" | populationB=="D10"]
  mscsubpondB$withinpond <- ifelse(mscsubpondB$populationA==mscsubpondB$populationB, 1, 0)
  ggplot(data=mscsubpondB, aes(x=as.factor(pondcompare), y=meanIBS, color=as.factor(withinpond))) + geom_beeswarm()
